# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c5f34944727e1bd8f9b1f8d6380c1d65606318ab9d462f9117f5e68cbf5ae68e383233af28933bd01195c5cca15a5ed6299bb8e48bd7ffcda8daf902de3ac92

test:
  secret_key_base: 8c78a905d694220ebd2b785f7d7b9a5d8d9e6237926b3ce0dcafadddfd9005c96736319562cfe643e97528f77fbec4d78248d545f61f8b7b6d5c542ae942a9c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
